### ISSUE TITLE
Using metrics to evaluate Features (Token) Selection

### ISSUE THREAD

**Issue by khalilmaachou** [jayded/eraserbenchmark#14]
Hello, 
First of all Thanks for the nice work!
Currently, i am using Lime (for example), to extract the list of features (tokens) with there score used to predict the sentiment of the movie reviews, and i am confused about the input you are giving to this function _score_aggregator so i can evaluate the token selection of lime for example, using the list of evidences as the real tokens .
Can you please let me know how can i use your function based on my token selection method ?
 Thank you very much!

**Comment by jayded** [comment]
I don't understand your question. 

If you're talking specifically about how to use the `_score_aggregator` function, it's used in [one method](https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/metrics.py#L237) and even has a type annotation. The `_score_aggregator` function is a scorer+averager. 

If you're computing an AUPRC over document/annotation pairs (typically there's a one-to-one correspondence; in the multidocument case (e.g. FEVER) that's not the case, which is why the actual inputs are tuples), it computes an AUPRC per document/annotation pair, and then averages. If that is unclear or if you have a question about this specifically, I recommend dropping an `import ipdb; ipdb.set_trace()` in the middle of the function when run through the main and inspecting step-by-step to see the intended usage. It is _not_ intended to be used outside this program. 

If you're asking about how to change one of these functions for your own use (it looks like you're using movies, so maybe this isn't relevant), I suggest using the [metrics front end](https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/metrics.py). The format is carefully documented [here](
https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/metrics.py#L547)
I think your inputs should look something like, in their most minimal form:
```python
{
        "annotation_id": str, required
        # these classifications *must not* overlap within the same document
        "rationales": List[
            {
                "docid": str, # required
                # token level classifications, a value must be provided per-token
                "soft_rationale_predictions": List[float], optional.
            }
        ],
  }
```
And then the contents will be read in from the appropriate data directory (specified in the commandline arguments). If you wanted something different (e.g. custom dataset) you could add it in a format matching how [ERASER handles loading](https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/utils.py#L123) (it might be easier to download some of the data and replicate that).

If you want something else, like _one_ of the metrics, you'll need to implement that, or pull it out explicitly.
