### ISSUE TITLE
Are trained models available?

### ISSUE THREAD

**Issue by jeslev** [jayded/eraserbenchmark#15]
Hello, thank you for sharing your work.
I'm trying to reproduce and play around with the metrics. However, I'm short of GPU memory for the training phase. Since I want to replicate your results, can you share the trained models? Or are they hosted anywhere? 

Thanks in advance.

**Comment by jayded** [comment]
The only trained models I have shreable are my reproduction of e-snli at https://drive.google.com/file/d/1F8qFtrKA5ZiDoSMbcfdtafMwZ7hGt4JI/view?usp=drive_link . This file and link will evaporate after I graduate.

The only reason I have this one around is because training seems to diverge half the time for this dataset and I never investigated why. e-snli and cos-e are probably the worst type of fit for ERASER as classifying individual tokens for relevance is just not a great fit for the pipeline approaches.

For other models you can probably safely reduce the batch size.
