### ISSUE TITLE
Question about training and evaluation on Movie dataset

### ISSUE THREAD

**Issue by zhaoxy92** [jayded/eraserbenchmark#8]
Hi, 

Thanks for the interesting work!

I have a question about the training and evaluation process on the movie data.

**My understanding is:**

For each movie document, there are multiple sentences and only some sentences include rationales. To train the model, you first train an evidence identifier on sentence level to classify if a particular sentence is an evidence.  Then you also train an evidence classifier on token level to classify if a token is a rationale token. 

In the prediction/inference phrase, you apply the token-level evidence classifier to only the sentences predicted as evidence by the sentence-level evidence identifier. 

**Could you please let me know if my understanding is correct? I couldn't find related explanations in the paper.**

**If my understanding is correct, I have a few questions:**

1. When you do sampling negative examples, do  you sample sentences only from the same document as pos examples, or randomly sample from all documents?
2. When you evaluate rationale extraction, do you evaluate against all document tokens, or only the tokens in gold evidence sentences?

Thank you very much!

**Comment by jayded** [comment]
Apologies for the delay - somehow repo notifications were off.

In general the right way to get in contact about detailed issues is email me at deyoung.j at northeastern.edu

In general there are three types of models trained for this repo:
1. A "bert-to-bert" model, which first identifies sentences via a BERT model and then classifies them. This classifier has no opinions about token level information.
2. A soft "token identifier" and then token classifier that selects tokens and passes them through a classifier over all kept tokens. This classifier has no opinions about sentence level information.
3. The lei-et-al models, described [here](https://github.com/successar/Eraser-Benchmark-Baseline-Models)

The first two models identify a unit of evidence (a sentence or a token) and then pass it to a classifier. There are no three stage models, contrary to the understanding above. Movies results are reported for models (1) and (3).

For the bert-to-bert model (1):
Movies is a relatively weak dataset, but in the pipeline model negative sentences are selected on a per document basis, by [this method call](https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/models/pipeline/evidence_identifier.py#L122) using [the random sampler](https://github.com/jayded/eraserbenchmark/blob/master/params/movies.json)  which is [defined here](https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/models/pipeline/evidence_identifier.py#L45). This may mean that some (in the case of movies, many) of the documents lack negatives. For lei-et-al, you'll need to consult [Sarthak's repo](https://github.com/successar/Eraser-Benchmark-Baseline-Models).

As for your second question - evaluation is discussed in section 6 of the paper and is a doozy. Our approach was generally "we don't know really know which metrics are the right ones, so we'll try all of them". If you have a specific question about this please shoot me an email.

If you're doing tests or actively working with this repo I would suggest you use movies for validation that your code runs rather than for validation of your methods. If you wanted to train a token-level version for movies, that might be possible but I doubt it would "just work" without modifying the codebase. If you wanted to start down that path, take a look at the [COS-E params](https://github.com/jayded/eraserbenchmark/blob/master/params/cose_bert.json#L7) but the data may be differently formatted given the dataset.
